export enum Configuration {
  PORT = 'PORT',
  MONGODB_URI = 'MONGODB_URI',
  RABBITMQ_URI = 'RABBITMQ_URI',
  HOST = 'HOST',
  WORK_TO_ME_URL = 'WORK_TO_ME_URL',
  WORK_TO_ME_PASSWORD = 'WORK_TO_ME_PASSWORD',
  WORK_TO_ME_LOGIN = 'WORK_TO_ME_LOGIN',
  BEDS_ONLINE_URL = 'BEDS_ONLINE_URL',
  BEDS_ONLINE_API_KEY = 'BEDS_ONLINE_API_KEY',
  BEDS_ONLINE_SECRET = 'BEDS_ONLINE_SECRET',
}
